export const QUESTION_API_URL = 'https://opentdb.com/api.php';
export const FETCH_QUESTIONS_LIST_REQUEST = 'FETCH_QUESTIONS_LIST_REQUEST';
export const FETCH_QUESTIONS_LIST_SUCCESS = 'FETCH_QUESTIONS_LIST_SUCCESS';
export const FETCH_QUESTIONS_LIST_ERROR = 'FETCH_QUESTIONS_LIST_ERROR';
